### ISSUE TITLE
python-slugify conflicts with awesome-slugify

### ISSUE THREAD

**Issue by lopezjimenezjesus** [aldryn/aldryn-translation-tools#12]
python-slugify conflicts with awesome-slugify

```
python manage.py syncdb 
ImportError: cannot import name Slugify
```

To work requires to uninstall python-slugify and awesome-slugify and then reinstall awesome-slugify.

**Comment by mkoistinen** [comment]
@jesusjl What would be the proposed solution for aldryn-translation-tools?

**Comment by lopezjimenezjesus** [comment]
No idea, just to let you know, but looks that awesome-slugify could be used instead.

Thank you mkoistinen.

**Comment by mkoistinen** [comment]
Yea. Its unfortunate when packages use the same package name as another package. Sometimes this is done intentionally to aide in converting a project from one package to another. Unfortunately, from a package-maintainer's perspective, it becomes a real challenge to make the change from one to the other, especially when migrations are involved (not the case here).
